### ISSUE TITLE
Relax libpq pin?

### ISSUE THREAD

**Issue by izahn** [conda-forge/soci-feedstock#11]
`soci-postgresql` cannot be installed with the most recent `libpq`:

```
 $ mamba create -q -n tmp --dry-run libpq=14.3 soci-postgresql
Encountered problems while solving:
  - package soci-postgresql-4.0.1-h4bd325d_0 requires libpq >=12.3,<13.0a0, but none of the providers can be installed
```

This is because `libpq` is pinned exactly in https://github.com/conda-forge/soci-feedstock/blob/70c74e57076d2ce9cdcfaafa2d2ceca15bb43e46/recipe/meta.yaml#L110 (`libpq` doesn't seem to use a third version component so `max_pin='x.x'` is an exact pin in this case. This means that `soci-postgresql` will need to be rebuilt for every `libpq` release, as I've done in https://github.com/conda-forge/soci-feedstock/pull/10 (please merge, I need this for https://github.com/conda-forge/rstudio-feedstock/pull/5)

Does it make sense to relax the `libpq` pin to `max_pin='x'`? If not maybe we can add `libpq` to the global pins so the bot will update for us.

**Comment by izahn** [comment]
Also, `libpq` does have run export now, so this can be dropped here.

**Comment by izahn** [comment]
Fixed now in https://github.com/conda-forge/soci-feedstock/pull/10, please merge that when you have a moment.

**Comment by marimeireles** [comment]
Thank you for the fix =)
