### ISSUE TITLE
Version 4.0.3 not uploaded

### ISSUE THREAD

**Issue by izahn** [conda-forge/soci-feedstock#8]
### Comment:

https://github.com/conda-forge/soci-feedstock/pull/7 was never uploaded to anaconda.org, the latest version there is still `4.0.2`. Maybe try pushing an empty commit to this repository and see if that will trigger a rebuild?

**Comment by marimeireles** [comment]
Hey @izahn, but this will never show up in anaconda.org, conda-forge is a parallel repository.
The way you should use it is by either adding the channel to your `rc` file or by adding the argument `-c conda-forge` when using your CLT :)
Unfortunately, I have no idea how to upload packages to anaconda!

**Comment by izahn** [comment]
No, conda-forge is hosted on anaconda.org e.g. https://anaconda.org/conda-forge/soci-core

Just push an empty commit and see it it triggers a rebuild

**Comment by izahn** [comment]
I prepared https://github.com/conda-forge/soci-feedstock/pull/9 for you, please merge it to trigger a rebuild so we can get 4.0.3 uploaded.
